// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace LegendPeak.Native
{
	public class AppleStoreResponse : EventArgs, IStoreResponse
	{
		public string productId { get; set; }
		public StoreResponseStatus status { get; set; }
		public string message { get; set; }
	}
}