//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace LegendPeak.Platforms
{
	public class PlatformRangeInfo
	{
		public int heightRange;
		public IEnumerable<int> prefabRange;

		public PlatformRangeInfo ()
		{
		}

		public PlatformRangeInfo(int heightRange, IEnumerable<int> prefabRange)
		{
			this.heightRange = heightRange;
			this.prefabRange = prefabRange;
		}
	}
		
}

