//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace LegendPeak.Platforms
{
	public class PlatformRangeInfo
	{
		public int heightRange;
		public int prefabRangeStart;
        public int prefabRangeEnd;

		public PlatformRangeInfo ()
		{
		}

		public PlatformRangeInfo(int heightRange, int prefabRangeStart, int prefabRangeEnd)
		{
			this.heightRange = heightRange;
            this.prefabRangeStart = prefabRangeStart;
		    this.prefabRangeEnd = prefabRangeEnd;
		}
	}
		
}

